title: Dashboard
lang: en
theme: system
checkUpdates: true

behaviour:
  target: _blank

layout:
  grid:
    small: 2
    medium: 2
    large: 3
    xlarge: 4


services:

  Favourites:

    - title: Karakeep
      description: Bookmarks
      link: https://bookmarks.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/karakeep.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: true

    - title: Google Gemini
      description: AI assistant
      link: https://gemini.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlegemini.svg
        wrap: true
        background: '#ffffff'

    - title: Proton Pass
      description: Password manager
      link:
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonpass.svg
        wrap: true
        background: '#ffffff'

    - title: Proton Mail
      description: Emails
      link: https://mail.proton.me/u/0/inbox
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonmail.svg
        wrap: true
        background: '#ffffff'

    - title: Unifi
      description: Home network
      link: https://unifi.ui.com/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/unifi.svg
        wrap: true
        background: '#0559C9'


    - title: Google Photos
      description: Personal photos and memories
      link: https://photos.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlephotos.svg
        wrap: true
        background: '#ffffff'

    - title: Google Calendar
      description: Personal scheduling
      link: https://calendar.google.com/calendar/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlecalendar.svg
        wrap: true
        background: '#ffffff'

    - title: Home Assistant
      description: Smart home
      link: https://home.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/homeassistant.svg
        wrap: true
        background: '#18BCF2'
      status:
        enabled: true
        animation: true

    - title: Vanguard
      description: Savings ISA
      link: https://secure.vanguardinvestor.co.uk/en-gb/customer/home/000-0000347898/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/vanguard.svg
        wrap: true
        background: '#96151D'

  Entertainment:

    - title: YouTube
      description: My subscriptions
      link: https://www.youtube.com/feed/subscriptions
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/youtube.svg
        wrap: true
        background: '#ffffff'

    - title: Plex
      description: Movies & TV
      link: http://65.108.239.185:42424/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/plex.svg
        wrap: true
        background: '#000000'
      status:
        enabled: true
        animation: true

    - title: BBC iPlayer
      description: TV from the beeb
      link: https://www.bbc.co.uk/iplayer
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbciplayer.svg
        wrap: true
        background: '#000000'

    - title: Yamtrack
      description: Media tracker & watchlist
      link: https://watchlist.harnett.uk/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/yamtrack.svg
        wrap: true
        background: '#212529'
      status:
        enabled: true
        animation: true

  News:

    - title: BBC News
      description: Latest UK news
      link: https://www.bbc.co.uk/news
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbcnews.svg
        wrap: true
        background: '#000000'

    - title: the Guardian
      description: UK news, analysis, & opinion
      link: https://www.theguardian.com/uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/theguardian.svg
        wrap: true
        background: '#1F2E60'

    - title: The Verge
      description: Tech news & reviews
      link: https://www.theverge.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/theverge.svg
        wrap: true
        background: '#4902F4'

    - title: Ars Technica
      description: Technology & science
      link: https://arstechnica.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/arstechnica.svg
        wrap: true
        background: '#000000'

    - title: FreshRSS
      description: My RSS feeds
      link: https://news.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/freshrss.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: true