title: Dashboard
lang: en
theme: system
checkUpdates: true

behaviour:
  target: _blank

layout:
  grid:
    small: 2
    medium: 2
    large: 3
    xlarge: 4


services:

  Favourites:

    - title: YouTube
      description: My subscriptions
      link: https://www.youtube.com/feed/subscriptions
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/youtube.svg
        wrap: true
        background: '#ffffff'

    - title: FreshRSS
      description: My RSS feeds
      link: https://news.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/freshrss.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: false

    - title: BBC News
      description: Homepage
      link: https://www.bbc.co.uk/news
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbcnews.svg
        wrap: true
        background: '#000000'

    - title: Plex
      description: Television and movies
      link: http://65.108.239.185:42424/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/plex.svg
        wrap: true
        background: '#000000'
      status:
        enabled: true
        animation: false

    - title: Karakeep
      description: Bookmark manager
      link: https://bookmarks.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/karakeep.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: false

    - title: The Verge
      description: The latest tech news and reviews
      link: https://www.theverge.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/theverge.svg
        wrap: true
        background: '#4902F4'

    - title: Google Gemini
      description: AI-powered assistant
      link: https://gemini.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlegemini.svg
        wrap: true
        background: '#ffffff'

    - title: Vanguard
      description: Savings account
      link: https://secure.vanguardinvestor.co.uk/en-gb/customer/home/000-0000347898/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/vanguard.svg
        wrap: true
        background: '#96151D'

    - title: Unifi
      description: Manage and monitor your UniFi network
      link: https://unifi.ui.com/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/unifi.svg
        wrap: true
        background: '#0559C9'

    - title: Proton Pass
      description:
      link:
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonpass.svg
        wrap: true
        background: '#ffffff'

    - title: Proton Mail
      description: View my emails
      link: https://mail.proton.me/u/0/inbox
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonmail.svg
        wrap: true
        background: '#ffffff'

    - title: Google Photos
      description: View my photos
      link: https://photos.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlephotos.svg
        wrap: true
        background: '#ffffff'

    - title: BBC iPlayer
      description: Watch content form the Beeb
      link: https://www.bbc.co.uk/iplayer
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbciplayer.svg
        wrap: true
        background: '#000000'

    - title: Google Calendar
      description: Manage my personal schedule
      link: https://calendar.google.com/calendar/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlecalendar.svg
        wrap: true
        background: '#ffffff'

    - title: Ars Technica
      description: News and opinions in technology, science and society
      link: https://arstechnica.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/arstechnica.svg
        wrap: true
        background: '#000000'