title: Dashboard
lang: en
theme: system
checkUpdates: true

behaviour:
  target: _blank

layout:
  grid:
    small: 2
    medium: 2
    large: 3
    xlarge: 4


services:

  Favourites:

    - title: YouTube
      description:
      link: https://www.youtube.com/feed/subscriptions
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/youtube.svg
        wrap: true
        background: '#ffffff'

    - title: FreshRSS
      description:
      link: https://news.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/freshrss.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: true

    - title: BBC News
      description:
      link: https://www.bbc.co.uk/news
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbcnews.svg
        wrap: true
        background: '#000000'

    - title: Plex
      description:
      link: http://65.108.239.185:42424/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/plex.svg
        wrap: true
        background: '#000000'
      status:
        enabled: true
        animation: true

    - title: Karakeep
      description:
      link: https://bookmarks.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/karakeep.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true
        animation: true

    - title: The Verge
      description:
      link: https://www.theverge.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/theverge.svg
        wrap: true
        background: '#4902F4'

    - title: Google Gemini
      description:
      link: https://gemini.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlegemini.svg
        wrap: true
        background: '#ffffff'

    - title: Vanguard
      description:
      link: https://secure.vanguardinvestor.co.uk/en-gb/customer/home/000-0000347898/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/vanguard.svg
        wrap: true
        background: '#96151D'

    - title: Unifi
      description:
      link: https://unifi.ui.com/dashboard
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/unifi.svg
        wrap: true
        background: '#0559C9'

    - title: Proton Pass
      description:
      link:
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonpass.svg
        wrap: true
        background: '#ffffff'

    - title: Proton Mail
      description:
      link: https://mail.proton.me/u/0/inbox
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/protonmail.svg
        wrap: true
        background: '#ffffff'

    - title: Google Photos
      description:
      link: https://photos.google.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlephotos.svg
        wrap: true
        background: '#ffffff'

    - title: BBC iPlayer
      description:
      link: https://www.bbc.co.uk/iplayer
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/bbciplayer.svg
        wrap: true
        background: '#000000'

    - title: Google Calendar
      description:
      link: https://calendar.google.com/calendar/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/googlecalendar.svg
        wrap: true
        background: '#ffffff'

    - title: Ars Technica
      description:
      link: https://arstechnica.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/arstechnica.svg
        wrap: true
        background: '#000000'

    - title: Home Assistant
      description:
      link: https://home.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/refs/heads/main/Icons/homeassistant.svg
        wrap: true
        background: '#000000'
      status:
        enabled: true
        animation: true