title: My Home Page
lang: en
theme: system
checkUpdates: true

behaviour:
  target: _blank

layout:
  grid:
    small: 2
    medium: 2
    large: 3
    xlarge: 4

tags:
  - name: Home
    color: yellow
  - name: Work
    color: blue


services:

  Favourites:
    - title: YouTube
      description: My subscriptions
      link: https://www.youtube.com/feed/subscriptions
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/youtube.svg
        wrap: true
        background: '#ffffff'

    - title: FreshRSS
      description: My RSS feeds
      link: https://news.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/freshrss.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true

    - title: BBC News
      description: Homepage
      link: https://www.bbc.co.uk/news
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/bbcnews.svg
        wrap: true
        background: '#000000'

    - title: Plex
      description: Television and movies
      link: http://65.108.239.185:42424/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/plex.svg
        wrap: true
        background: '#000000'
      status:
        enabled: true

    - title: Karakeep
      description: Bookmark manager
      link: https://bookmarks.harnett.uk
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/karakeep.svg
        wrap: true
        background: '#ffffff'
      status:
        enabled: true

    - title: The Verge
      description: The latest tech news and reviews
      link: https://www.theverge.com/
      target: _self
      icon:
        url: https://raw.githubusercontent.com/RobertHarnett/Mafl-Icons/1acc77136f9d9ae413f28da0fd5cad718d0fdb55/Icons/theverge.svg
        wrap: true
        background: '#ffffff'


  Home:
    - title: Home Assistant
      description: Home automation system
      link: '#'
      icon:
        name: simple-icons:homeassistant
        wrap: true
        color: '#3dbcf3'
      tags:
        - Home
    - title: AdGuard
      description: Ad blocking service
      link: '#'
      icon:
        name: simple-icons:adguard
        wrap: true
        color: '#68bc71'

  Cloud:
    - title: Traefik
      description: Cloud edge router
      link: '#'
      icon:
        name: devicon:traefikproxy
        wrap: true
    - title: Portainer
      description: Docker container management
      link: '#'
      icon:
        name: devicon:portainer
        wrap: true
    - title: Grafana
      description: Server monitoring dashboards
      link: '#'
      icon:
        name: logos:grafana
        wrap: true

  Devices:
    - title: Router
      description: Keenetic Peak
      link: '#'
      icon:
        name: bi:router-fill
        wrap: true
    - title: NAS
      description: Network storage
      link: '#'
      icon:
        name: mdi:nas
        wrap: true